set number
set laststatus=2
set smarttab
set expandtab
set tabstop=4
set shiftwidth=4
syntax on
set clipboard=unnamed,autoselect
set noswapfile
set whichwrap=b,s,h,l,<,>,[,]
set mouse=a
"set ttymouse=xterm2
set background=dark
